/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestaoPessoal;

/**
 *
 * @author lirioramalheira
 */
public class EditarEmpregado extends javax.swing.JFrame {

    /**
     * Creates new form EditarEmpregado
     */
    public EditarEmpregado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelDepartamento = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelNFuncionario = new javax.swing.JLabel();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldNFuncionario = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldSenha = new javax.swing.JTextField();
        jComboBoxDepartamento = new javax.swing.JComboBox<>();
        jComboBoxGenero = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelNome.setText("Nome:");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(10, 10, 160, 40);

        jLabelGenero.setText("Genero:");
        getContentPane().add(jLabelGenero);
        jLabelGenero.setBounds(10, 50, 170, 40);

        jLabelDepartamento.setText("Departamento:");
        getContentPane().add(jLabelDepartamento);
        jLabelDepartamento.setBounds(10, 90, 210, 40);

        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(10, 130, 160, 40);

        jLabelNFuncionario.setText("Nº de Funcionário:");
        getContentPane().add(jLabelNFuncionario);
        jLabelNFuncionario.setBounds(10, 170, 160, 40);

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizar);
        jButtonAtualizar.setBounds(210, 220, 100, 29);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(330, 220, 98, 29);

        jTextFieldNFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNFuncionario);
        jTextFieldNFuncionario.setBounds(140, 170, 300, 40);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(80, 10, 360, 40);
        getContentPane().add(jTextFieldSenha);
        jTextFieldSenha.setBounds(80, 130, 360, 40);

        jComboBoxDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RH", "Contabilidade", "Gestão de Recursos", "Gestão de Stock" }));
        jComboBoxDepartamento.setToolTipText("Departamentos existentes"); // NOI18N
        jComboBoxDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepartamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDepartamento);
        jComboBoxDepartamento.setBounds(120, 90, 320, 40);

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        getContentPane().add(jComboBoxGenero);
        jComboBoxGenero.setBounds(80, 60, 360, 27);

        setSize(new java.awt.Dimension(445, 306));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // String nome, String genero, String departamento, String senha, String nFuncionario
        Empregado novoEmpregado = new Empregado(jTextFieldNome.getText(),jComboBoxGenero.getSelectedItem().toString(),
            jComboBoxDepartamento.getSelectedItem().toString(),
            jTextFieldSenha.getText(),jTextFieldNFuncionario.getText());
        //gravar dados do empregado no ficheiro registo historico
        try{
            FileWriter registoHist = new FileWriter(registoHistorico.getName(), true);
            BufferedWriter entradaH = new BufferedWriter(registoHist);
            entradaH.newLine();
            entradaH.write(novoEmpregado.obterNumeroEmpregado()+";"
                +novoEmpregado.obterSenha()+";"+novoEmpregado.obterNome()+";"
                +novoEmpregado.obterSexo()+";"+novoEmpregado.obterCargo()+";"
                +novoEmpregado.obterEAtivo());
            entradaH.close();
        }
        catch(IOException ex){
            JOptionPane.showConfirmDialog(rootPane, "Foi impssivel registar novo Empregado!");
        }
        //Apresentação de uma tela de dialogo
        JOptionPane.showConfirmDialog(rootPane, "Empregado cadastrado");
        dispose();
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
        new TelaGestaoPessoal().setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldNFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNFuncionarioActionPerformed
        //
    }//GEN-LAST:event_jTextFieldNFuncionarioActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jComboBoxDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEmpregado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxDepartamento;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNFuncionario;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JTextField jTextFieldNFuncionario;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSenha;
    // End of variables declaration//GEN-END:variables
}
